config/routes.rb
Rails.application.routes.draw do
  root to: "transaction_orders#index"
  get 'transactions/new'
  get 'pages/offline', as: :offline
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :transaction_orders
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :parent_account, optional: true, class_name: 'Account'
  has_many :transaction_orders
  has_many :transactions

  delegate :email, to: :user, allow_nil: true, prefix: true
  after_create :generate_number, :assign_parent

  class << self
    def parent_account_for(currency)
      find_by(currency: currency, internal: true)
    end
  end

  def all_others
    Account.where.not(id: id).where(currency: currency, internal: nil)
  end

  def deposit(amount)
    TransferService.new(amount: amount, number: number).transfer_from(parent_account)
  end

  def credit(amount)
    raise 'Invalid amount' unless amount.positive?

    transaction do
      decrement!(:balance, amount)
      raise 'Balance went negative' if balance.negative?
    end
  end

  def debit(amount)
    raise 'Invalid amount' unless amount.positive?

    transaction do
      increment!(:balance, amount)
    end
  end

  def max_available_amount
    FeeCalculatorService.new(amount: balance).max_for_balance
  end

  private

  def generate_number
    number = (100_000_000 + id).to_s
    check_digit = Helpers::CheckDigitHelper.checksum731(number)
    update(number: "#{number}#{check_digit}")
  end

  def assign_parent
    return if internal?

    update(parent_account: self.class.parent_account_for('EUR'))
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  include AASM

  belongs_to :account
  belongs_to :transaction_order

  validates :transaction_type, presence: true

  scope :date_between, ->(search) {
    return none if search.invalid?

    where(created_at: search.start_date.beginning_of_day..search.end_date.end_of_day)
  }

  before_create :process_credit, :process_debit, :store_balance

  def store_balance
    self.balance = account.balance
  end

  def process_credit
    return unless credit?

    account.credit(amount)
  end

  def process_debit
    return unless debit?

    account.debit(amount)
  end

  def signed_amount
    return amount if debit?

    -amount
  end

  def html_class
    return 'text-green-400' if debit?
    
    'text-red-300'
  end
end

app/models/transaction_order.rb
class TransactionOrder < ApplicationRecord
  include AASM

  belongs_to :account
  has_many :transactions

  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0.01, less_than_or_equal_to: :max_available_amount }
  validates :number, presence: true
  validates :state, presence: true
  validates :to_account, presence: true

  delegate :currency, to: :account, allow_nil: true
  delegate :max_available_amount, to: :account, allow_nil: true, prefix: true

  after_create :start_process

  aasm column: 'state' do # rubocop:disable Metrics/BlockLength
    state :pending, initial: true
    state :processing
    state :completed
    state :failed

    event :process, after_commit: %i[mark_started transfer_amount] do
      transitions from: :pending, to: :processing
    end

    event :done, after_commit: %i[mark_completed] do
      transitions from: :processing, to: :completed
    end

    event :fail do
      transitions from: :processing, to: :failed
    end
  end

  def max_available_amount
    account_max_available_amount || 0.to_d
  end

  def mark_started
    update_column(:transaction_started_at, Time.zone.now)
  end

  def mark_completed
    update_column(:transaction_completed_at, Time.zone.now)
  end

  def to_account
    Account.find_by(currency: currency, internal: nil, number: number)
  end

  def fee
    FeeCalculatorService.new(amount: amount).fee
  end

  def start_process
    process!
  end

  private

  def transfer_amount
    self.transaction do
      if account.internal?
        transactions.create!(account: account, amount: amount, credit: true, transaction_type: :outgoing)
        transactions.create!(account: to_account, amount: amount, debit: true, transaction_type: :incoming)
      else
        transactions.create!(account: account, amount: fee, credit: true, transaction_type: :transfer_fee)
        transactions.create!(account: account, amount: amount, credit: true, transaction_type: :outgoing)
        transactions.create!(account: account.parent_account, amount: fee, debit: true, transaction_type: :fee_revenue)
        transactions.create!(account: to_account, amount: amount, debit: true, transaction_type: :incoming)
      end
      done!
      return
    end
  rescue => e
    Rails.logger.error(e)
    delay.fail!
    raise ActiveRecord::Rollback
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :create_account!, :deposit_10k

  has_one :account

  validates :email, presence: true, email: true, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }

  def deposit_10k
    account.deposit(10_000)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :show_bank_offline!, unless: :bank_online?
  before_action :authenticate_user!, if: :bank_online?

  private

  def bank_online?
    Account.parent_account_for('EUR').present?
  end

  def show_bank_offline!
    render 'pages/offline', layout: 'offline'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/transaction_orders_controller.rb
class TransactionOrdersController < ApplicationController
  def index
    @search = TransactionSearchService.new(**search_params.deep_symbolize_keys)
    @simple = search_params.blank?
    return if current_user.account.blank?
    return unless @search.valid?

    @transactions = current_user.account.transactions.date_between(@search)
    @transaction_orders = current_user.account.transaction_orders
  end

  def new
    @transaction = TransferService.new
  end

  def create
    @transaction = TransferService.new(**transaction_params)

    if @transaction.transfer_from(current_user.account)
      flash.notice = 'Transfer successful'
      redirect_to transaction_orders_path
    else
      render :new
    end
  end

  private

  def transaction_params
    params.require(:transfer_service).permit(:amount, :number).to_h.deep_symbolize_keys
  end

  def search_params
    return {} if params[:transaction_search_service].blank?

    params.require(:transaction_search_service).permit(:start_date, :end_date).to_h
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/_flash_messages.html.slim
.flash-messages
  - if notice
    div[role="notice"]
      .bg-blue-500.text-white.font-bold.rounded-t.px-4.py-2
        |  Notice
      .border.border-t-0.border-blue-400.rounded-b.bg-blue-100.px-4.py-3.text-blue-700
        p
          = notice
  - if alert
    div[role="alert"]
      .bg-red-500.text-white.font-bold.rounded-t.px-4.py-2
        |  Warning
      .border.border-t-0.border-red-400.rounded-b.bg-red-100.px-4.py-3.text-red-700
        p
          = alert

app/views/layouts/_header.html.slim
header.mb-4
div[data-controller="toggle"]
  nav.flex.flex-wrap.items-center.justify-between.px-3.py-3.text-gray-700.bg-gray-100.lg:px-10[data-controller="hello"]
    .flex.items-center.mr-6.flex-no-shrink
      = link_to root_path, class:"link text-xl tracking-tight font-semibold" do
        = image_pack_tag 'small_logo.png'
      - if user_signed_in?
        .pl-2.font-semibold
          = number_with_precision(current_user.account&.balance, precision: 2)
          span> €&nbsp;
    .block.lg:hidden
      button.flex.items-center.px-3.py-2.border.border-gray-500.rounded.text-grey.hover:text-gray-600.hover:border-gray-600[data-action="click->toggle#toggle"]
        svg.w-3.h-3.fill-current[viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"]
          title
            | Menu
          path[d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"]
    .hidden.items-center.block.w-full.text-center.lg:flex-1.lg:flex.lg:text-left[data-target="toggle.toggle"]
      .lg:flex-grow
        - if user_signed_in?
          = link_to 'Send Money', new_transaction_order_path, class: "block mt-4 lg:inline-block lg:mt-0 lg:mr-4 mb-2 lg:mb-0 link"
          - if current_user&.account&.transactions.present?
            = link_to 'Payment History', transaction_orders_path, class: "block mt-4 lg:inline-block lg:mt-0 lg:mr-4 mb-2 lg:mb-0 link"
      .items-center.block.w-full.mt-2.text-center.lg:flex.lg:flex-row.lg:flex-1.lg:mt-0.lg:text-left.lg:justify-end
        - if user_signed_in?
          = link_to "Edit account", edit_user_registration_path, class: "btn btn-default mb-2 lg:mr-2 lg:mb-0 block"
          = link_to "Log out", destroy_user_session_path, method: :delete, class:"btn btn-default mb-2 lg:mb-0 block"
        - else
          = link_to "Login", new_user_session_path, class:"btn btn-default mb-2 lg:mr-2 lg:mb-0 block"
          = link_to "Sign Up", new_user_registration_path, class:"btn btn-default block"

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[charset="UTF-8"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      | SimpleBank
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/header'
    = render 'layouts/flash_messages'
    = yield

app/views/layouts/offline.html.slim
doctype html
html
  head
    meta[charset="UTF-8"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    meta[equiv="refresh" content="5"]
    title
      | SimpleBank
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container.mx-auto.p-8
      .mx-auto.lg:max-w-sm
        = link_to root_path do
          .py-10.text-center
            = image_pack_tag 'logo.png'
            .float-right
              = render 'pages/subtitle'
        .bg-white.rounded.shadow
          .border-b.py-8.font-bold.text-black.text-center.text-xl.tracking-widest.uppercase
            |  Currently offline, please check back later
          = yield

app/views/pages/_subtitle.html.erb
<svg 
 xmlns="http://www.w3.org/2000/svg"
 xmlns:xlink="http://www.w3.org/1999/xlink"
 width="242px" height="22px">
<text kerning="auto" font-family="Myriad Pro" fill="rgb(0, 0, 0)" transform="matrix( 0.73130081667137, 0, 0, 0.73130081667137,0.77806586871179, 16.8445561268377)" font-size="30px"><tspan font-size="30px" font-family="Lato" fill="#262626">keeping&#32;banking&#32;simple</tspan></text>
</svg>

app/views/pages/offline.html.slim
p If you are the administrator of the page
pre rails bank:setup

app/views/transaction_orders/_compact_list.html.slim
.bg-white.rounded.shadow
  .font-bold.text-black.tracking-widest.uppercase
    |  Payment History
  = simple_form_for(@search, url: transaction_orders_path, method: :get, input_html: {class: 'g-grey-lightest px-10 py-10'}) do |f|
    .form-inputs.flex
      .mb-3.w-1/2
        = f.input :start_date, required: false, input_html: { class: 'border w-full' }
      .mb-3.w-1/2
        = f.input :end_date, required: false, input_html: { class: 'border w-full' }
    .form-actions
      .flex
        = f.button :submit, "Show", class: 'bg-green-600 hover:bg-green-700 w-full text-sm text-white uppercase font-bold tracking-wider'
= render('transaction_orders/transactions', transactions: @transactions.sort_by(&:created_at))

app/views/transaction_orders/_search.html.slim
.container.mx-auto.p-8
  .mx-auto.lg:max-w-sm
    = link_to root_path do
      .py-10.text-center
        = image_pack_tag 'logo.png'
        .float-right
          = render 'pages/subtitle'
    .bg-white.rounded.shadow
      .border-b.py-8.font-bold.text-black.text-center.text-xl.tracking-widest.uppercase
        |  Payment History
      = simple_form_for(@search, url: transaction_orders_path, method: :get, input_html: {class: 'g-grey-lightest px-10 py-10'}) do |f|
        .form-inputs
          .mb-6
            = f.input :start_date, required: false, input_html: { class: 'border w-full p-3' }
          .mb-6
            = f.input :end_date, required: false, input_html: { class: 'border w-full p-3' }
        .form-actions
          .flex
            = f.button :submit, "Show", class: 'bg-green-600 hover:bg-green-700 w-full p-4 text-sm text-white uppercase font-bold tracking-wider'

app/views/transaction_orders/_transaction_orders.html.slim
pre
  - (transaction_orders || []).each do |transaction_order|
    = JSON.pretty_generate(transaction_order.attributes)

app/views/transaction_orders/_transactions.html.slim
table
  tr
    th From
    th To
    th Type
    th Amount
    th Date
    th Balance
  - (transactions || []).group_by(&:transaction_order).each do |transaction_order, connected_transactions|
    tr.border-t
      td.pr-6
        = AccountPresenter.new(transaction_order.account).name
      td.pr-6
        = AccountPresenter.new(transaction_order.to_account).name
      td[colspan="4"]
    - connected_transactions.each do |transaction|
      tr 
        td
        td
        td= transaction.transaction_type
        td[class="#{transaction.html_class} font-bold float-right px-2"]= number_with_precision(transaction.signed_amount, precision: 2)
        td= transaction.created_at.to_date
        td.float-right.font-semibold= number_with_precision(transaction.balance, precision: 2)

app/views/transaction_orders/index.html.slim
- if @simple
  = render 'search'
- else
  = render 'compact_list'

app/views/transaction_orders/new.html.slim
.container.mx-auto.p-8
  .mx-auto.lg:max-w-sm
    = link_to root_path do
      .py-10.text-center
        = image_pack_tag 'logo.png'
        .float-right
          = render 'pages/subtitle'
    .bg-white.rounded.shadow
      .border-b.py-8.font-bold.text-black.text-center.text-xl.tracking-widest.uppercase
        |  Send money
      = simple_form_for(@transaction, url: transaction_orders_path, input_html: {class: 'g-grey-lightest px-10 py-10'}) do |f|
        .form-inputs
          .mb-3
            = f.input :number, collection: current_user.account.all_others.map { |account| AccountPresenter.new(account) }, label_method: :name, value_method: :number, include_blank: false, input_html: {class: 'border w-full p-3'}
          .mb-6
            = f.input :amount, required: true, input_html: { class: 'border w-full p-3' }
        .form-actions
          .flex
            = f.button :submit, "Send", class: 'bg-green-600 hover:bg-green-700 w-full p-4 text-sm text-white uppercase font-bold tracking-wider'